
GET http://localhost:5106/minimalApi/movie

####

Post http://localhost:5106/minimalApi/postMovie
Content-Type: application/json

{
  "Title": "King kung",
  "Description": "Good movie",
  "Genre": "Action",
  "AgeLimit": 18,
  "Language": "English",
  "UnderText": "Underlying text",
  "Actors": ["Jakc", "Joe"],
  "Direction": ["Davod"],
  "ReleaseDate": "2023-05-15",
  "Time": "12:30:00"
}

####

Post http://localhost:5106/minimalApi/postMovie
Content-Type: application/json

{
  "Title": "The Dark Jungle",
  "Description": "Good movie",
  "Genre": "Action",
  "AgeLimit": 18,
  "Language": "English",
  "UnderText": "Underlying text",
  "Actors": ["Jakc", "Joe"],
  "Direction": ["Davod"],
  "ReleaseDate": "2023-05-15",
  "Time": "12:30:00"
}

####

DELETE http://localhost:5106/minimalApi/deleteMovie?title=Bad%20Guy
Content-Type: application/json


#### DEn ska fixas______________________
DELETE  http://localhost:5106/minimalApi/deleteMovie
Content-Type: application/json

{
  "Title": "Bad Guy"
}

