

Get http://localhost:5204/salon


####

Post http://localhost:5204/salon
Content-Type: application/json

{
  "Name": "Small",
  "Nummber": 15,
  "ChairQuantity": 50
}

####

DELETE http://localhost:5204/salon/11
Content-Type: application/json



