
#### Salon ______________________________________________________________________________________________
Get http://localhost:5204/salon

####

Post http://localhost:5204/salon
Content-Type: application/json

{
  "Name": "Small",
  "Nummber": 22,
  "ChairQuantity": 30
}

####

DELETE http://localhost:5204/salon/24
Content-Type: application/json

#### Movie ___________________________________________________________________________________________________

Get http://localhost:5204/movie

####

Post http://localhost:5204/movie
Content-Type: application/json
  
{
  "Title": "Stars War",
  "Description": "War between Humans and Aliens",
  "Genre": "Action",
  "AgeLimit": 15,
  "Language": "English",
  "UnderText": "Underlying text",
  "Actors": ["Jack Jones", "Sara Tailer"],
  "Direction": ["Steven Spielberg"],
  "ReleaseDate": "2021-05-15",
  "Time": "02:30:00"
}

####

DELETE http://localhost:5204/movie/17
Content-Type: application/json

#### CinemaViewing ______________________________________________________________________________________________

Get http://localhost:5204/CinemaViewing

####
GET http://localhost:5204/CinemaViewing/uppcoming

####
Post http://localhost:5204/CinemaViewing
Content-Type: application/json
  
{
  "MovieId": 15,
  "SalonId": 22,
  "TimeAndDate": "2021-01-10T21:20:00",
  "Price": 250,
  "PlaceQuantity": 10,
  "Premiere": "2024"
}

####

DELETE http://localhost:5204/CinemaViewing/20
Content-Type: application/json

####  Reservation ______________________________________________________________________________________________

Get http://localhost:5204/reservation

####

Post http://localhost:5204/reservation
Content-Type: application/json
  
{
  "CinemaViewingId": 14,
  "Quantity": 3,
  "ReservationCode": "",
  "Email": "jack.gmail.com"
}

#### 
# Här hämtas alla reservationer som tillhör en CinemaViewing
GET http://localhost:5204/reservation/CinemaViewing/19

####
DELETE http://localhost:5204/reservation/37


####

