
#### Salon ______________________________________________________________________________________________
Get http://localhost:5204/salon

####

Post http://localhost:5204/salon
Content-Type: application/json

{
  "Name": "Small",
  "Nummber": 2,
  "ChairQuantity": 30
}

####

DELETE http://localhost:5204/salon/24
Content-Type: application/json

#### Movie ___________________________________________________________________________________________________

Get http://localhost:5204/movie

####

Get http://localhost:5204/movie/1

####

Post http://localhost:5204/movie
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJzdWIiOiJ1c2VyIiwianRpIjoiZDZmZGVjOTgiLCJyb2xlIjoiYWRtaW4iLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1NzIxNiIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzM3IiwiaHR0cDovL2xvY2FsaG9zdDo1MjA0IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzA3OCJdLCJuYmYiOjE3MTIwOTIxMjMsImV4cCI6MTcxOTk1NDUyMywiaWF0IjoxNzEyMDkyMTI0LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.aVkvwirzM1JcwOeH0sYkXQHfQQ_GP3PAN6WYU0CCwho
Content-Type: application/json
  
{
  "Title": "Spider-Man: Homecoming",
  "Description": "Peter Parker tries to balance his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man.",
  "Genre": "Action, Adventure, Sci-Fi",
  "AgeLimit": 12,
  "Language": "English",
  "UnderText": "English",
  "Actors": ["Tom Holland", "Michael Keaton", "Zendaya"],
  "Direction": ["Jon Watts"],
  "ReleaseDate": "2017-07-07",
  "Time": "02:13:00",
  "ImageUrl": "https://th.bing.com/th/id/OIP.o3oFScb8i7J3BqbO-EPbUwHaNK?rs=1&pid=ImgDetMain"
}

####

DELETE http://localhost:5204/movie/3
Content-Type: application/json

#### CinemaViewing ______________________________________________________________________________________________

Get http://localhost:5204/CinemaViewing

####
GET http://localhost:5204/CinemaViewing/uppcoming

####
Post http://localhost:5204/CinemaViewing
Content-Type: application/json
  
{
  "MovieId": 5,
  "SalonId": 2,
  "TimeAndDate": "2024-05-15T21:20:00",
  "Price": 250,
  "PlaceQuantity": 30,
  "Premiere": "2024"
}

####

DELETE http://localhost:5204/CinemaViewing/22
Content-Type: application/json

####  Reservation ______________________________________________________________________________________________

Get http://localhost:5204/reservation

####

GET http://localhost:5204/reservation/59


####

GET http://localhost:5204/reservation/updateReservationCodeStatus/62

####

Post http://localhost:5204/reservation
Content-Type: application/json
  
{
  "CinemaViewingId": 23,
  "Quantity": 5,
  "Email": "Emma@gmail.com"
}

#### 
# Här hämtas alla reservationer som tillhör en CinemaViewing
GET http://localhost:5204/reservation/CinemaViewing/23

####
DELETE http://localhost:5204/reservation/61



###
GET https://api.adviceslip.com/advice

